### ISSUE TITLE
ip resolve and https

### ISSUE THREAD

**Issue by mgholam** [4zv4l/zproxy#1]
Hi,

I would like to connect to a domain name instead of an ip address, and also the destination is a https proxy, can you help with this?
( i.e. https://proxysite.net:8888 )

**Comment by 4zv4l** [comment]
for the domain name instead of ip I can implement that but for now I get a weird behavior when using my proxy as http proxy, when the target server's connection is closed (so for http this happen often), the program will just stop and I still don't know why yet.

**Comment by mgholam** [comment]
Does this code support forward proxy i.e routing local traffic to destination proxy server?

**Comment by 4zv4l** [comment]
yeah I guess, it's a really basic proxy, it takes all the data coming in input and forward it to the output and forward all data coming from output to the input.

**Comment by 4zv4l** [comment]
I just pushed the commit to add domain name support, tell me if it works for you

**Comment by mgholam** [comment]
I don't get address errors but my ip addresses are not working, do you have a working proxy address that I can test with ?

**Comment by 4zv4l** [comment]
I don't, I try on my local network and it works using both ip and domain name/hostname.
Also I fixed the SIGPIPE error so now it should never quit if there is a connection error

**Comment by mgholam** [comment]
Found an ip address that is active, but does not connect:
```sh
./proxy 9090    64.189.24.250    3129
```

**Comment by 4zv4l** [comment]
after doing this if you connect to localhost:9090 it will send all data to 64.189.24.250:3129
this is supposed to work

**Comment by mgholam** [comment]
Ah! then the code is not a forward proxy!

I want to set my browsers proxy to `localhost:9090` and browse to `www.google.com` and have the traffic go through `64.189.24.250:3129`

**Comment by 4zv4l** [comment]
forward proxy is the default proxy (not a reverse proxy then)
and that's what my code does, if from a place you wanna join `google.com` but it's forbidden you can use my program to make a proxy server with another name allowing you to still join `google.com`

**Comment by 4zv4l** [comment]
> The forward proxy server, as a proxy for a client, will help a client request an origin server which a client may be hard to request directly

> For example, if one client is blocked by the origin server, this client can use a forward proxy server to request the content from the origin server and returns it to the client

**Comment by 4zv4l** [comment]
just my proxy bridge one client with one server which is known

**Comment by mgholam** [comment]
I'm currently using https://github.com/snail007/goproxy which is great and written in go and was looking for a similar project in zig/c etc..

**Comment by 4zv4l** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/46655455/181754990-f842a171-e972-4fbb-b58f-8bac80373227.png">

Just did a test and it works
You can redirect to another proxy
Just mine is really simple so it's basic tcp/ip packets
So you can redirect all your traffic through that port you open (that point to the proxy you want)
and that should be good

**Comment by mgholam** [comment]
Try to browse with with your browser's proxy set to `localhost:9090`:
```
./proxy 9090   20.47.108.204   8888
```

**Comment by 4zv4l** [comment]
That server is reported as unsafe

**Comment by 4zv4l** [comment]
and that's not how a proxy works also xD

**Comment by 4zv4l** [comment]
when you run my program it creates a bridge between itself and the address you gave.
after it's to you to send the right data on that bridge, as I showed you with curl and a double proxy, it works.
